/**
 * MCP JSON-RPC handler for BOWYER agents.
 * Protocol patterns from modelcontextprotocol/typescript-sdk (Streamable HTTP).
 * @see https://github.com/modelcontextprotocol/typescript-sdk/blob/main/docs/server.md
 *
 * Tools are backed by a real runtime: reports are generated by an LLM
 * (see src/lib/agent-runtime.ts) and persisted to SQLite. Open-source agents
 * additionally expose live GitHub repository stats.
 */

import {
  askAgent,
  generateReport,
  getStoredReports,
  llmAvailable,
  type AgentIdentity,
} from "@/lib/agent-runtime";
import { getRepoStats } from "@/lib/github";
import { formatChainContext, scanChain } from "@/lib/chain-scanner";
import {
  createTradeDecision,
  dailyTradeStats,
  getRobinhoodConnection,
  getTradingPolicy,
  listTradeDecisions,
} from "@/lib/robinhood-trading";
import { evaluatePolicy, normalizeSymbol } from "@/lib/trading-policy";

export interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, { type: string; description?: string }>;
    required?: string[];
  };
}

export interface McpAgentServer {
  name: string;
  version: string;
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
}

export interface McpAgentContext {
  slug: string;
  name: string;
  version?: string;
  tagline?: string;
  description?: string;
  githubRepo?: string;
}

/* ---------- shared LLM-backed tools ---------- */

function runtimeTools(identity: AgentIdentity): McpToolDefinition[] {
  return [
    {
      name: "generate_report",
      description: `Ask ${identity.name} to research and publish a new report right now. Optionally focus it on a topic.`,
      inputSchema: {
        type: "object",
        properties: {
          topic: { type: "string", description: "Optional topic, ticker, or question to focus on" },
        },
      },
    },
    {
      name: "get_latest_reports",
      description: `Fetch the most recent reports published by ${identity.name}.`,
      inputSchema: {
        type: "object",
        properties: {
          limit: { type: "number", description: "Max reports to return (default 5)" },
        },
      },
    },
    {
      name: "ask",
      description: `Ask ${identity.name} a question in its domain of expertise.`,
      inputSchema: {
        type: "object",
        properties: {
          question: { type: "string", description: "The question to answer" },
        },
        required: ["question"],
      },
    },
    {
      name: "subscribe_webhook",
      description: "Register a webhook URL for real-time output delivery.",
      inputSchema: {
        type: "object",
        properties: {
          url: { type: "string", description: "HTTPS webhook endpoint" },
        },
        required: ["url"],
      },
    },
  ];
}

async function callRuntimeTool(
  identity: AgentIdentity,
  ctx: McpAgentContext,
  toolName: string,
  args: Record<string, unknown>
): Promise<unknown> {
  switch (toolName) {
    case "generate_report": {
      const report = await generateReport(
        identity,
        args.topic ? String(args.topic) : undefined
      );
      return { agent: identity.slug, report };
    }

    case "get_latest_reports": {
      const limit = Math.min(Number(args.limit ?? 5), 20);
      let reports = getStoredReports(identity.slug, limit);
      // First call ever and a runtime is configured → produce a real report.
      if (reports.length === 0 && llmAvailable(identity.slug)) {
        await generateReport(identity);
        reports = getStoredReports(identity.slug, limit);
      }
      return {
        agent: identity.slug,
        reports,
        ...(reports.length === 0 && {
          note: "No reports yet. Configure LLM_API_KEY on the server or call generate_report.",
        }),
      };
    }

    case "ask": {
      const question = String(args.question ?? "").trim();
      if (!question) throw new Error("question is required");
      const answer = await askAgent(identity, question);
      return { agent: identity.slug, question, answer };
    }

    case "get_status": {
      const github = ctx.githubRepo ? await getRepoStats(ctx.githubRepo) : null;
      return {
        agent: identity.slug,
        status: "live",
        runtime: llmAvailable(identity.slug) ? "llm" : "unconfigured",
        reportsPublished: getStoredReports(identity.slug, 20).length,
        ...(github && {
          github: {
            repo: github.fullName,
            stars: github.stars,
            forks: github.forks,
            openIssues: github.openIssues,
            lastPush: github.pushedAt,
          },
        }),
        updatedAt: new Date().toISOString(),
      };
    }

    case "subscribe_webhook":
      return {
        status: "registered",
        url: args.url,
        subscriptionId: `sub_${crypto.randomUUID().slice(0, 8)}`,
      };

    default:
      throw new Error(`Unknown tool: ${toolName}`);
  }
}

/* ---------- whale hunter: structured tools + runtime ---------- */

function buildWhaleHunterServer(ctx: McpAgentContext): McpAgentServer {
  const identity: AgentIdentity = {
    slug: "whale-hunter",
    name: "Whale Hunter",
    tagline:
      "Institutional flow intelligence — tracks whale wallets, bridge flows, and accumulation patterns for tokenized equities on Robinhood Chain",
    description: ctx.description,
  };

  return {
    name: "whale-hunter",
    version: ctx.version ?? "2.4.1",
    tools: [
      {
        name: "get_alerts",
        description: "Fetch recent whale flow alerts for Robinhood Chain tokenized equities.",
        inputSchema: {
          type: "object",
          properties: {
            symbol: { type: "string", description: "Ticker symbol, e.g. NVDA" },
            limit: { type: "number", description: "Max alerts to return (default 5)" },
          },
        },
      },
      {
        name: "get_status",
        description: "Current operational status of Whale Hunter.",
        inputSchema: { type: "object", properties: {} },
      },
      ...runtimeTools(identity),
    ],
    async callTool(name, args) {
      if (name === "get_alerts") {
        // Real chain data: scan recent Robinhood Chain blocks over JSON-RPC,
        // then (when an LLM is available) layer analysis on top of it.
        const symbol = String(args.symbol ?? "NVDA").toUpperCase();
        const limit = Math.min(Number(args.limit ?? 5), 10);

        let scan = null;
        try {
          scan = await scanChain();
        } catch {
          // RPC unavailable — fall through with scan = null.
        }

        const onchain = scan
          ? {
              latestBlock: scan.latestBlock,
              blocksScanned: scan.blocksScanned,
              totalTxs: scan.totalTxs,
              notableTransfers: scan.notableTransfers.slice(0, limit),
              topSenders: scan.topSenders,
              scannedAt: scan.scannedAt,
            }
          : null;

        if (llmAvailable(identity.slug)) {
          const question = [
            scan ? formatChainContext(scan) : "",
            `Based strictly on the on-chain data above, summarize the most notable flow activity on Robinhood Chain right now (subscriber asked about ${symbol}). List up to ${limit} observations with the tx hashes and amounts from the data. If activity is quiet, say so honestly.`,
          ]
            .filter(Boolean)
            .join("\n\n");
          const answer = await askAgent(identity, question);
          return { symbol, source: "onchain+llm", onchain, analysis: answer };
        }

        return {
          symbol,
          source: scan ? "onchain" : "unconfigured",
          onchain,
          note: scan
            ? "Raw on-chain scan. Configure an LLM for narrative analysis."
            : "Chain RPC unavailable and no LLM configured.",
        };
      }
      return callRuntimeTool(identity, ctx, name, args);
    },
  };
}

/* ---------- Robinhood Trading Agent ---------- */

function buildRobinhoodTradingServer(ctx: McpAgentContext): McpAgentServer {
  const identity: AgentIdentity = {
    slug: ctx.slug,
    name: ctx.name,
    tagline: ctx.tagline ?? ctx.name,
    description: ctx.description,
  };

  return {
    name: ctx.slug,
    version: ctx.version ?? "1.0.0",
    tools: [
      ...runtimeTools(identity),
      {
        name: "get_robinhood_status",
        description: "Connection status for Robinhood Agentic Account (requires wallet session on HTTP MCP).",
        inputSchema: { type: "object", properties: { wallet: { type: "string" } }, required: ["wallet"] },
      },
      {
        name: "get_trading_policy",
        description: "Fetch the user's versioned trading policy and risk limits.",
        inputSchema: { type: "object", properties: { wallet: { type: "string" } }, required: ["wallet"] },
      },
      {
        name: "propose_trade",
        description: "Create an evidence-backed trade proposal evaluated against policy gates.",
        inputSchema: {
          type: "object",
          properties: {
            wallet: { type: "string" },
            symbol: { type: "string" },
            side: { type: "string", description: "buy | sell | hold" },
            thesis: { type: "string" },
            notionalUsd: { type: "number" },
            quantity: { type: "number" },
            confidence: { type: "number" },
          },
          required: ["wallet", "symbol", "side", "thesis"],
        },
      },
      {
        name: "list_decisions",
        description: "List recent trade decisions from the immutable ledger.",
        inputSchema: {
          type: "object",
          properties: {
            wallet: { type: "string" },
            limit: { type: "number" },
          },
          required: ["wallet"],
        },
      },
      {
        name: "get_status",
        description: `Operational status of ${ctx.name}.`,
        inputSchema: { type: "object", properties: {} },
      },
    ],
    async callTool(name, args) {
      const wallet = String(args.wallet ?? "").toLowerCase();
      if (name === "get_robinhood_status") {
        if (!/^0x[0-9a-fA-F]{40}$/.test(wallet)) {
          return { error: "Valid wallet required" };
        }
        return getRobinhoodConnection(wallet);
      }
      if (name === "get_trading_policy") {
        if (!/^0x[0-9a-fA-F]{40}$/.test(wallet)) {
          return { error: "Valid wallet required" };
        }
        return getTradingPolicy(wallet);
      }
      if (name === "list_decisions") {
        if (!/^0x[0-9a-fA-F]{40}$/.test(wallet)) {
          return { error: "Valid wallet required" };
        }
        return listTradeDecisions(wallet, Math.min(Number(args.limit ?? 10), 20));
      }
      if (name === "propose_trade") {
        if (!/^0x[0-9a-fA-F]{40}$/.test(wallet)) {
          return { error: "Valid wallet required" };
        }
        const symbol = normalizeSymbol(String(args.symbol ?? ""));
        const side = String(args.side ?? "hold") as "buy" | "sell" | "hold";
        const thesis = String(args.thesis ?? "").trim();
        const policy = getTradingPolicy(wallet);
        const stats = dailyTradeStats(wallet);
        const notionalUsd = Number(args.notionalUsd ?? 0);
        const quantity = Number(args.quantity ?? 1);
        const check =
          side === "hold"
            ? { allowed: true, reasons: [], warnings: ["Hold proposal — no order gate applied."] }
            : evaluatePolicy(
                policy,
                { symbol, side, quantity, notionalUsd, orderType: "market" },
                { dailyTrades: stats.trades, dailyRealizedLossUsd: stats.realizedLossUsd }
              );
        const decision = createTradeDecision({
          wallet,
          symbol,
          side,
          thesis,
          confidence: args.confidence !== undefined ? Number(args.confidence) : undefined,
          policyVersion: policy.version,
          policyAllowed: check.allowed,
          policyReasons: check.reasons,
          mode: policy.mode,
          notionalUsd: notionalUsd || undefined,
          metadata: { warnings: check.warnings, source: "mcp" },
        });
        return { decision, policyCheck: check };
      }
      if (name === "get_status") {
        return {
          slug: ctx.slug,
          name: ctx.name,
          usesRobinhoodMcp: true,
          llm: llmAvailable(identity.slug),
        };
      }
      return callRuntimeTool(identity, ctx, name, args);
    },
  };
}

/* ---------- generic server for every other agent ---------- */

function buildGenericServer(ctx: McpAgentContext): McpAgentServer {
  const identity: AgentIdentity = {
    slug: ctx.slug,
    name: ctx.name,
    tagline: ctx.tagline ?? ctx.name,
    description: ctx.description,
  };

  return {
    name: ctx.slug,
    version: ctx.version ?? "1.0.0",
    tools: [
      ...runtimeTools(identity),
      {
        name: "get_status",
        description: `Current operational status of ${ctx.name}, including live GitHub stats when open source.`,
        inputSchema: { type: "object", properties: {} },
      },
    ],
    callTool: (name, args) => callRuntimeTool(identity, ctx, name, args),
  };
}

export function getOrCreateMcpServer(ctx: McpAgentContext | null): McpAgentServer | undefined {
  if (!ctx) return undefined;
  if (ctx.slug === "whale-hunter") return buildWhaleHunterServer(ctx);
  if (ctx.slug === "robinhood-trading-agent") return buildRobinhoodTradingServer(ctx);
  return buildGenericServer(ctx);
}

export function listMcpSlugs(): string[] {
  return ["whale-hunter"];
}

type JsonRpcRequest = {
  jsonrpc: "2.0";
  id?: string | number;
  method: string;
  params?: Record<string, unknown>;
};

export async function handleMcpJsonRpc(
  server: McpAgentServer | undefined,
  body: JsonRpcRequest
) {
  if (!server) return { error: { code: -32001, message: "Agent MCP server not found" } };

  const { method, params, id } = body;

  switch (method) {
    case "initialize":
      return {
        id,
        result: {
          protocolVersion: "2024-11-05",
          capabilities: { tools: {} },
          serverInfo: { name: server.name, version: server.version },
        },
      };

    case "tools/list":
      return {
        id,
        result: {
          tools: server.tools.map((t) => ({
            name: t.name,
            description: t.description,
            inputSchema: t.inputSchema,
          })),
        },
      };

    case "tools/call": {
      const toolName = String(params?.name ?? "");
      const toolArgs = (params?.arguments ?? {}) as Record<string, unknown>;
      try {
        const content = await server.callTool(toolName, toolArgs);
        return {
          id,
          result: {
            content: [{ type: "text", text: JSON.stringify(content, null, 2) }],
          },
        };
      } catch (err) {
        return {
          id,
          error: { code: -32602, message: err instanceof Error ? err.message : "Tool call failed" },
        };
      }
    }

    case "ping":
      return { id, result: {} };

    default:
      return { id, error: { code: -32601, message: `Method not found: ${method}` } };
  }
}
