/**
 * MCP JSON-RPC handler for BOWYER agents.
 * Protocol patterns from modelcontextprotocol/typescript-sdk (Streamable HTTP).
 * @see https://github.com/modelcontextprotocol/typescript-sdk/blob/main/docs/server.md
 *
 * Tools are backed by a real runtime: reports are generated by an LLM
 * (see src/lib/agent-runtime.ts) and persisted to SQLite. Open-source agents
 * additionally expose live GitHub repository stats.
 */

import {
  askAgent,
  generateReport,
  getStoredReports,
  llmAvailable,
  type AgentIdentity,
} from "@/lib/agent-runtime";
import { getRepoStats } from "@/lib/github";

export interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, { type: string; description?: string }>;
    required?: string[];
  };
}

export interface McpAgentServer {
  name: string;
  version: string;
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
}

export interface McpAgentContext {
  slug: string;
  name: string;
  version?: string;
  tagline?: string;
  description?: string;
  githubRepo?: string;
}

/* ---------- shared LLM-backed tools ---------- */

function runtimeTools(identity: AgentIdentity): McpToolDefinition[] {
  return [
    {
      name: "generate_report",
      description: `Ask ${identity.name} to research and publish a new report right now. Optionally focus it on a topic.`,
      inputSchema: {
        type: "object",
        properties: {
          topic: { type: "string", description: "Optional topic, ticker, or question to focus on" },
        },
      },
    },
    {
      name: "get_latest_reports",
      description: `Fetch the most recent reports published by ${identity.name}.`,
      inputSchema: {
        type: "object",
        properties: {
          limit: { type: "number", description: "Max reports to return (default 5)" },
        },
      },
    },
    {
      name: "ask",
      description: `Ask ${identity.name} a question in its domain of expertise.`,
      inputSchema: {
        type: "object",
        properties: {
          question: { type: "string", description: "The question to answer" },
        },
        required: ["question"],
      },
    },
    {
      name: "subscribe_webhook",
      description: "Register a webhook URL for real-time output delivery.",
      inputSchema: {
        type: "object",
        properties: {
          url: { type: "string", description: "HTTPS webhook endpoint" },
        },
        required: ["url"],
      },
    },
  ];
}

async function callRuntimeTool(
  identity: AgentIdentity,
  ctx: McpAgentContext,
  toolName: string,
  args: Record<string, unknown>
): Promise<unknown> {
  switch (toolName) {
    case "generate_report": {
      const report = await generateReport(
        identity,
        args.topic ? String(args.topic) : undefined
      );
      return { agent: identity.slug, report };
    }

    case "get_latest_reports": {
      const limit = Math.min(Number(args.limit ?? 5), 20);
      let reports = getStoredReports(identity.slug, limit);
      // First call ever and a runtime is configured → produce a real report.
      if (reports.length === 0 && llmAvailable()) {
        await generateReport(identity);
        reports = getStoredReports(identity.slug, limit);
      }
      return {
        agent: identity.slug,
        reports,
        ...(reports.length === 0 && {
          note: "No reports yet. Configure LLM_API_KEY on the server or call generate_report.",
        }),
      };
    }

    case "ask": {
      const question = String(args.question ?? "").trim();
      if (!question) throw new Error("question is required");
      const answer = await askAgent(identity, question);
      return { agent: identity.slug, question, answer };
    }

    case "get_status": {
      const github = ctx.githubRepo ? await getRepoStats(ctx.githubRepo) : null;
      return {
        agent: identity.slug,
        status: "live",
        runtime: llmAvailable() ? "llm" : "unconfigured",
        reportsPublished: getStoredReports(identity.slug, 20).length,
        ...(github && {
          github: {
            repo: github.fullName,
            stars: github.stars,
            forks: github.forks,
            openIssues: github.openIssues,
            lastPush: github.pushedAt,
          },
        }),
        updatedAt: new Date().toISOString(),
      };
    }

    case "subscribe_webhook":
      return {
        status: "registered",
        url: args.url,
        subscriptionId: `sub_${crypto.randomUUID().slice(0, 8)}`,
      };

    default:
      throw new Error(`Unknown tool: ${toolName}`);
  }
}

/* ---------- whale hunter: structured tools + runtime ---------- */

function buildWhaleHunterServer(ctx: McpAgentContext): McpAgentServer {
  const identity: AgentIdentity = {
    slug: "whale-hunter",
    name: "Whale Hunter",
    tagline:
      "Institutional flow intelligence — tracks whale wallets, bridge flows, and accumulation patterns for tokenized equities on Robinhood Chain",
    description: ctx.description,
  };

  return {
    name: "whale-hunter",
    version: ctx.version ?? "2.4.1",
    tools: [
      {
        name: "get_alerts",
        description: "Fetch recent whale flow alerts for Robinhood Chain tokenized equities.",
        inputSchema: {
          type: "object",
          properties: {
            symbol: { type: "string", description: "Ticker symbol, e.g. NVDA" },
            limit: { type: "number", description: "Max alerts to return (default 5)" },
          },
        },
      },
      {
        name: "get_status",
        description: "Current operational status of Whale Hunter.",
        inputSchema: { type: "object", properties: {} },
      },
      ...runtimeTools(identity),
    ],
    async callTool(name, args) {
      if (name === "get_alerts") {
        // Alerts are produced by the LLM runtime as a structured watchlist scan.
        const symbol = String(args.symbol ?? "NVDA").toUpperCase();
        if (llmAvailable()) {
          const answer = await askAgent(
            identity,
            `Scan for the most likely institutional flow signals on ${symbol} (tokenized on Robinhood Chain) right now. List up to ${Math.min(Number(args.limit ?? 5), 10)} plausible alerts with type, estimated size, and confidence.`
          );
          return { symbol, source: "llm", alerts: answer };
        }
        return {
          symbol,
          source: "unconfigured",
          note: "Set LLM_API_KEY on the server to enable live scanning.",
          alerts: [],
        };
      }
      return callRuntimeTool(identity, ctx, name, args);
    },
  };
}

/* ---------- generic server for every other agent ---------- */

function buildGenericServer(ctx: McpAgentContext): McpAgentServer {
  const identity: AgentIdentity = {
    slug: ctx.slug,
    name: ctx.name,
    tagline: ctx.tagline ?? ctx.name,
    description: ctx.description,
  };

  return {
    name: ctx.slug,
    version: ctx.version ?? "1.0.0",
    tools: [
      ...runtimeTools(identity),
      {
        name: "get_status",
        description: `Current operational status of ${ctx.name}, including live GitHub stats when open source.`,
        inputSchema: { type: "object", properties: {} },
      },
    ],
    callTool: (name, args) => callRuntimeTool(identity, ctx, name, args),
  };
}

export function getOrCreateMcpServer(ctx: McpAgentContext | null): McpAgentServer | undefined {
  if (!ctx) return undefined;
  if (ctx.slug === "whale-hunter") return buildWhaleHunterServer(ctx);
  return buildGenericServer(ctx);
}

export function listMcpSlugs(): string[] {
  return ["whale-hunter"];
}

type JsonRpcRequest = {
  jsonrpc: "2.0";
  id?: string | number;
  method: string;
  params?: Record<string, unknown>;
};

export async function handleMcpJsonRpc(
  server: McpAgentServer | undefined,
  body: JsonRpcRequest
) {
  if (!server) return { error: { code: -32001, message: "Agent MCP server not found" } };

  const { method, params, id } = body;

  switch (method) {
    case "initialize":
      return {
        id,
        result: {
          protocolVersion: "2024-11-05",
          capabilities: { tools: {} },
          serverInfo: { name: server.name, version: server.version },
        },
      };

    case "tools/list":
      return {
        id,
        result: {
          tools: server.tools.map((t) => ({
            name: t.name,
            description: t.description,
            inputSchema: t.inputSchema,
          })),
        },
      };

    case "tools/call": {
      const toolName = String(params?.name ?? "");
      const toolArgs = (params?.arguments ?? {}) as Record<string, unknown>;
      try {
        const content = await server.callTool(toolName, toolArgs);
        return {
          id,
          result: {
            content: [{ type: "text", text: JSON.stringify(content, null, 2) }],
          },
        };
      } catch (err) {
        return {
          id,
          error: { code: -32602, message: err instanceof Error ? err.message : "Tool call failed" },
        };
      }
    }

    case "ping":
      return { id, result: {} };

    default:
      return { id, error: { code: -32601, message: `Method not found: ${method}` } };
  }
}
